### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by childrenoftheblade** [kwacky1/text-adventure#30]
```[tasklist]
### to-do
- [x] when a party member's morale reaches 0, they give up on the adventure (unless they are the last member left). message: "[name] doesn't have any hope anymore. They left the party."
- [ ] https://github.com/kwacky1/text-adventure/issues/31
- [x] [implement illness and infection as described in the google document](https://github.com/kwacky1/text-adventure/issues/54)
- [x] add trait descriptions when selecting them
- [x] add all trait effects
- [x] higher morale gives you a chance of landing a critical hit on an enemy
- [x] lower morale gives you a chance of missing a hit on an enemy
- [ ] https://github.com/kwacky1/text-adventure/issues/39
```
