### ISSUE TITLE
trait effects to-do

### ISSUE THREAD

**Issue by childrenoftheblade** [kwacky1/text-adventure#32]
```[tasklist]
### Tasks
- [x] satiated: when food is consumed, the food is more effective by 0.5
- [x] friendly: when a new party member joins, they start as acquaintances instead of strangers
- [x] friendly: cannot reach "cold" with other members (minimum strangers)
- [x] scavenger: gets an 10% chance to gain a food item (this does not add to the preexisting chance, so it would be possible to get 2 items) message: "[name] was able to scavenge for some extra food."
- [x] scavenger: when an enemy is defeated, you gain a food item. message: "[name] made food with some... questionable meat."
- [x] resilient: add a message when they randomly heal: "[name] is feeling a bit better."
- [x] optimistic: add a message when morale is randomly raised: "[name] looks happy today."
- [x] fighter: when attacking an enemy, deal an extra damage
- [x] fighter: when attacking an enemy, have a chance to attack two at the same time
- [x] hungry: when given a ration or a snack, hunger is not restored. message: "That food didn't make [name] feel much better."
- [x] disconnected: when a new party member joins, they start as cold instead of strangers
- [x] disconnected: cannot reach "family" with other members (maximum friends)
- [x] depressed: add a message when morale is randomly lowered: "[name] has been crying."
- [x] clumsy: add a message when injury is randomly raised: "[name] tripped and hurt themself."
- [x] clumsy: when attacking an enemy, deal 1 less damage```
```
