### ISSUE TITLE
ToDos

### ISSUE THREAD

**Issue by kwacky1** [kwacky1/text-adventure#4]
```[tasklist]
### Tasks
- [ ] https://github.com/kwacky1/text-adventure/issues/6
- [x] Medical Supplies
- [ ] https://github.com/kwacky1/text-adventure/issues/9
- [ ] https://github.com/kwacky1/text-adventure/issues/7
- [ ] https://github.com/kwacky1/text-adventure/issues/8
- [ ] https://github.com/kwacky1/text-adventure/issues/49
```
